"""Regenerate vivarium_workbench/static/ai-models.js from marimo's llm-info registry.

    uv run scripts/gen_ai_models.py <marimo-checkout>/packages/llm-info/data [<git-sha>]

marimo (Apache-2.0, https://github.com/marimo-team/marimo) keeps one curated model list per
provider; the AI panel's model dropdown shows exactly that list, so the workbench mirrors it
rather than asking each endpoint. Only providers the workbench supports are emitted; Google is
limited to Gemini models (marimo's list also carries Vertex-hosted third-party ids).
"""
import json
import sys
from pathlib import Path

import yaml

# workbench provider id -> (marimo id, label)
PROVIDERS = {
    "openai": ("openai", "OpenAI"),
    "anthropic": ("anthropic", "Anthropic"),
    "google": ("google", "Google AI"),
    "ollama": ("ollama", "Ollama"),
    "opencode": ("opencode-go", "OpenCode Go"),
    "bedrock": ("bedrock", "Amazon Bedrock"),
}


def main(data_dir: Path, sha: str = "main") -> str:
    models = yaml.safe_load((data_dir / "models.yml").read_text())
    info = {p["id"]: p for p in yaml.safe_load((data_dir / "providers.yml").read_text())}
    out = {}
    for ours, (theirs, label) in PROVIDERS.items():
        entries = models.get(theirs, [])
        if ours == "google":
            entries = [m for m in entries if m["model"].startswith("gemini")]
        seen: set[str] = set()          # the upstream lists repeat a few ids (bedrock); keep the first
        entries = [m for m in entries if not (m["model"] in seen or seen.add(m["model"]))]
        out[ours] = {
            "label": label,
            "description": info[theirs]["description"],
            "url": info[theirs]["url"],
            "models": [{"name": m["name"], "model": m["model"], "description": m.get("description", ""),
                        "thinking": "thinking" in (m.get("capabilities") or [])} for m in entries],
        }
    body = json.dumps(out, indent=1, ensure_ascii=False)
    return (f"// GENERATED by scripts/gen_ai_models.py from marimo's llm-info registry (Apache-2.0,\n"
            f"// https://github.com/marimo-team/marimo, packages/llm-info/data @ {sha}). Do not edit.\n"
            f"window.VivAiModels = {body};\n")


if __name__ == "__main__":
    text = main(Path(sys.argv[1]), *(sys.argv[2:3]))
    Path(__file__).resolve().parent.parent.joinpath("vivarium_workbench/static/ai-models.js").write_text(text)
